#BASE IMAGE
FROM python:3.10.10

#NO .PYC FILES
ENV PYTHONDONTWRITEBYTECODE 1
#PYTHON SHOULDNT BUFFERE INPUT/OUTPUT
ENV PYTHONUNBUFFERED 1

#DEFAULT WORK DIRECTORY
WORKDIR /code

#COPY PIPFILES
COPY Pipfile Pipfile.lock /code/
#RUN THESE COMMANDS 
RUN pip install pipenv && pipenv install --system

#COPY PRESENT FOLDERS CODE TO /CODE IN DOCKER
COPY . /code/